### PR TITLE
Small Fix RU.lang

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by TheVizzy** [comment]
Merge it!

**Comment by Adaptivity** [comment]
First: your PR completely reverts mine. Second: No, your changes are incorrect, Thaumic Energistics mostly follows Thaumcraft translation. Thaumcraft ru_RU.lang uses capitalized form of "вы" as well as all other mods. So, I against it...

**Comment by TheVizzy** [comment]
Yes i know. Don't add this!

**Comment by TheVizzy** [comment]
Я посмотрел уже. Но все же в некоторых словах были ошибки с падежами.

**Pull request closed without merging**
