### PR TITLE
Killed most of dependency hell (yes, legit term) to gradle.

### PR DESCRIPTION
**Pull request by rallias**
Gradle is meant to automate building, that includes resolving dependencies.

### CODE REVIEW

**Comment by Nividica** [comment]
I'll give this a shot and see if it breaks anything in my current dev environment.
I had this big long post explaining why it might, but github just ate it. -.-

**Comment by rallias** [comment]
Well, you'll need to remove cofh*, NEI, IC2, and WAILA from libs/, but no major breakage should occur.

**Comment by Nividica** [comment]
I actually didn't have any issues at all. It just built it like normal.
And the big issue that I explained, and github ate, was NEI. In short, I have to do some seriously weird shit to the NEI jar in order to get eclipse to launch debug mode. I end up with two NEI jars. A non coremod, and the core mod, and god forbid if they are in the same folder. *sigh* still have no idea why I have to go through all that, but If I don't debug mode simply will not launch, no matter what changes I make to the buildpath.

**Comment by rallias** [comment]
Yeah, that's a problem with NEI. You might have to backdate your Waila
dep to 1.5.2a (a version I'm fairly sure works right).

**Comment by Nividica** [comment]
Is there an issue with 1.5.10?

**Comment by rallias** [comment]
The issue stems from CodeChickenCore, not Waila, but Waila 1.5.10 deps the crap version.

**Comment by rallias** [comment]
Anyhow, I always build and then copy the built versions over to a testing instance rather than running runServer/runClient.

**Comment by Nividica** [comment]
Interesting, I usually just leave the debug version running and make changes as I need to. Took a bit to get the hotswapper to work with me, but now I can usually just leave it MC open and code away.

**Pull request merged**
